### Register a user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "verifiedUser3",
    "name": "Verified User3",
    "email": "ezehsuccess0476@gmail.com",
    "password": "testingWonder"
}

### Verify email
PATCH http://localhost:3000/api/users/verifyEmail/:fd7112edce3c6e39cfbaca60d08bbf05f6f65a77
Content-Type: application/json

### Login with username
POST http://localhost:3000/api/users/loginWithUsername
Content-Type: application/json

{
    "username": "vscodeUser",
    "password": "testingWonder"
}

### Login with email
POST http://localhost:3000/api/users/loginWithEmail
Content-Type: application/json

{
    "email": "success1stclass@gmail.com",
    "password": "testingWonder"
}

### Get users
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Get user details
GET http://localhost:3000/api/users/636a24ee1f6e4b6770ed4935
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Edit user details
PATCH  http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

{
    "name": "Edit User",
    "username": "editUser"
}

### Create post
POST  http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

{
    "title": "Testing Post",
    "body": "This is a testing post"
}

### Get all posts
GET   http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Get post
GET   http://localhost:3000/api/posts/6359169f84fa70cdf512a387
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Edit post
PATCH   http://localhost:3000/api/posts/6359169f84fa70cdf512a387
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

{
    "title": "Edit Post",
    "body": "This is a editing post"
}

### Edit post
DELETE    http://localhost:3000/api/posts/6359169f84fa70cdf512a387
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw


## Production
### Register a user
POST https://my-nodejs-typescript.onrender.com/api/users/register
Content-Type: application/json

{
    "username": "liveUser",
    "name": "Live User",
    "email": "liveuser@gmail.com",
    "password": "testingLive"
}

### Login with username
POST https://my-nodejs-typescript.onrender.com/api/users/loginWithUsername
Content-Type: application/json

{
    "username": "liveUser",
    "password": "testingLive"
}

### Login with email
POST https://my-nodejs-typescript.onrender.com/api/users/loginWithEmail
Content-Type: application/json

{
    "email": "liveuser@gmail.com",
    "password": "testingLive"
}

### Get users
GET https://my-nodejs-typescript.onrender.com/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmU4NmUwNmQ5MGYxOTU2ODMyYTZiOSIsImlhdCI6MTY2ODE5MDY1NSwiZXhwIjoxNjY4Mjc3MDU1fQ.ETxByBk_dV7-y-24xwP-sJIopJvIwJ4cY61Z0ywDT3U

### Get user details
GET https://my-nodejs-typescript.onrender.com/api/users/636e86e06d90f1956832a6b9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Edit user details
PATCH  https://my-nodejs-typescript.onrender.com/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

{
    "name": "Edit User",
    "username": "editUser"
}
### Create post
POST  https://my-nodejs-typescript.onrender.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmU4NmUwNmQ5MGYxOTU2ODMyYTZiOSIsImlhdCI6MTY2ODE5MDY1NSwiZXhwIjoxNjY4Mjc3MDU1fQ.ETxByBk_dV7-y-24xwP-sJIopJvIwJ4cY61Z0ywDT3U

{
    "title": "Live creator",
    "body": "This is the first live post"
}

### Get all posts
GET   https://my-nodejs-typescript.onrender.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Get post
GET   https://my-nodejs-typescript.onrender.com/api/posts/636e92950826c264f3851da1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

### Edit post
PATCH  https://my-nodejs-typescript.onrender.com/api/posts/6359169f84fa70cdf512a387
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw

{
    "title": "Edit Post",
    "body": "This is a editing post"
}

### Edit post
DELETE    https://my-nodejs-typescript.onrender.com/api/posts/6359169f84fa70cdf512a387
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmUzNDczZTZhZGZhMWNjZDNkM2RmOCIsImlhdCI6MTY2ODE2NzE1NCwiZXhwIjoxNjY4MjUzNTU0fQ.eeytbUS_Sz08gOj_Sqa2ANP0GOxhtOl_E-uP0aokXTw
